### ISSUE TITLE
Configuration Example

### ISSUE THREAD

**Issue by sogabe** [CumulusNetworks/ptm#1]
I would like to test ptmd in my linux boxes. Please let us know how to write a configuration file.

**Comment by skamithi** [comment]
I'm working on a  ptmd demo using ansible. http://github.com/skamithi/ptmd_demo. I have config files in there. still also learning ptmd.

**Comment by sogabe** [comment]
Hello skamithi,
Thank you so much for pointing me your configurations!
I found good resources in Cumulus's support site.

**Comment by natm** [comment]
You can find some sample topology.dot files included in the presentation I gave at UKNOF26 in September - http://indico.uknof.org.uk/getFile.py/access?contribId=8&resId=1&materialId=slides&confId=28

Let me know if I can help out at all.

**Comment by sogabe** [comment]
Hello natm,
Thank you!. That is the most precise information.
