### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by cpalmer9** [CumulusNetworks/ptm#3]
Hi there,
We are getting the following errors when running 'make'.

Should the result of system(cmd) be assigned to something that then be checked?

ptm_conf.c: In function 'ptm_conf_topo_action':
ptm_conf.c:138: error: ignoring return value of 'system', declared with attribute warn_unused_result
ptm_conf.c:143: error: ignoring return value of 'system', declared with attribute warn_unused_result
cc1: warnings being treated as errors
ptm_event.c: In function 'main':
ptm_event.c:562: error: ignoring return value of 'fscanf', declared with attribute warn_unused_result
ptm_event.c:581: error: ignoring return value of 'daemon', declared with attribute warn_unused_result
ptm_event.c:584: error: ignoring return value of 'ftruncate', declared with attribute warn_unused_result

In file included from /usr/include/stdio.h:932,
                 from ptm_event.h:6,
                 from ptm_lldp.c:17:
In function 'snprintf',
    inlined from 'ptm_init_lldp' at ptm_lldp.c:791:
/usr/include/bits/stdio2.h:65: error: call to __builtin___snprintf_chk will always overflow destination buffer

**Comment by kanrajag** [comment]
Which environment are you compiling in ? I will try to repro it locally.

**Comment by cpalmer9** [comment]
Oracle Linux Server release 6.3
gcc-4.4.6-4.el6.x86_64
glibc-headers-2.12-1.80.el6_3.6.x86_64

**Comment by kanrajag** [comment]
Chris
is this still an issue?

**Comment by cpalmer9** [comment]
We've worked around it. I'm going to try and rebuild against Oracle Linux Server release 6.5 at some point to see if things are cleaner.

**Comment by cpalmer9** [comment]
I didn't see this issue when I rebuilt PTM on an OEL 6.5 Server.
